name: tf-checks
on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:
jobs:
  mysql-backup:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@feat/update-tf 
    with:
      working_directory: './examples/mysql-backup/'
      provider: gcp
 
  mysql-pvt:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@feat/update-tf 
    with:
      working_directory: './examples/mysql-private/'
      provider: gcp

  # mysql-public:
  #   uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@1.2.6
  #   with:
  #     working_directory: './examples/mysql-public/'

  # psql-backup:
  #   uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@1.2.6
  #   with:
  #     working_directory: './examples/psql-backup/'

  # psql-iam:
  #   uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@1.2.6
  #   with:
  #     working_directory: './examples/psql-iam/'

  # psql-private:
  #   uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@1.2.6
  #   with:
  #     working_directory: './examples/psql-private/'

  # psql-public:
  #   uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@1.2.6
  #   with:
  #     working_directory: './examples/psql-public/'